import React from "react";
import {
  Sparkles,
  Code2,
  MessageSquareText,
  BarChart3,
  Target,
  Brain,
} from "lucide-react";

const features = [
  {
    icon: Sparkles,
    title: "AI Generated Questions",
    description:
      "Get interview questions generated by AI based on your selected job role and experience level.",
  },
  {
    icon: Code2,
    title: "Technical Practice",
    description:
      "Practice technical questions and improve your knowledge before attending real interviews.",
  },
  {
    icon: MessageSquareText,
    title: "AI Answer Evaluation",
    description:
      "Submit your answers and get AI-powered feedback to understand your strengths and mistakes.",
  },
  {
    icon: BarChart3,
    title: "Performance Analysis",
    description:
      "Check your score and understand which areas need more practice and improvement.",
  },
  {
    icon: Target,
    title: "Role-Based Preparation",
    description:
      "Prepare specifically for roles such as React Developer, MERN Stack Developer and more.",
  },
  {
    icon: Brain,
    title: "Smart Interview Preparation",
    description:
      "Build confidence through structured practice designed to make your interview preparation easier.",
  },
];

const Features = () => {
  return (
    <section
      id="features"
      className="py-20 px-6 bg-slate-950 text-white"
    >
      <div className="max-w-7xl mx-auto">

        {/* Section Heading */}
        <div className="text-center max-w-2xl mx-auto mb-12">
          <p className="text-blue-500 font-semibold uppercase tracking-wider text-sm">
            Features
          </p>

          <h2 className="text-3xl md:text-4xl font-bold mt-2">
            Everything You Need to
            <span className="text-blue-500"> Prepare Better</span>
          </h2>

          <p className="text-gray-400 mt-4 leading-7">
            CareerPrep AI provides powerful tools to help you practice,
            evaluate your answers, and become more confident for your next
            technical interview.
          </p>
        </div>

        {/* Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">

          {features.map((feature, index) => {
            const Icon = feature.icon;

            return (
              <div
                key={index}
                className="group p-6 rounded-2xl bg-slate-900 border border-slate-800 hover:border-blue-500/50 hover:-translate-y-1 transition-all duration-300"
              >
                {/* Icon */}
                <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center mb-5 group-hover:bg-blue-500/20 transition">
                  <Icon
                    size={24}
                    className="text-blue-500"
                  />
                </div>

                {/* Title */}
                <h3 className="text-xl font-semibold mb-3">
                  {feature.title}
                </h3>

                {/* Description */}
                <p className="text-gray-400 text-sm leading-6">
                  {feature.description}
                </p>
              </div>
            );
          })}

        </div>
      </div>
    </section>
  );
};

export default Features;
